const data = {
    products: [
        {
            id:'1',
            name: 'Clatita uriasa',
            category: 'Shirts',
            image: './images/p1.jpg',
            price: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            id:'2',
            name: 'Clatita uriasa',
            category: 'Shirts',
            image: './images/p2.jpg',
            price: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            id:'3',
            name: 'Clatita uriasa',
            category: 'Shirts',
            image: './images/p3.jpg',
            price: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            id:'4',
            name: 'Clatita uriasa',
            category: 'Shirts',
            image: './images/p4.jpg',
            price: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            id:'5',
            name: 'Clatita uriasa',
            category: 'Shirts',
            image: './images/p5.jpg',
            price: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            id:'6',
            name: 'Clatita uriasa',
            category: 'Shirts',
            image: './images/p6.jpg',
            price: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews:10,
            description: 'high quality product',
        },
    ],
};

export default data;